#!/bin/bash
echo -e "\nmark-installs install script, by Mark Johnson"
if [[ $UID -ne 0 ]]; then
	echo -e "You must be root to run this script.\n"
	exit 2
fi
if [[ $# -eq 0 || "$1" != "-i" && "$1" != "-u" && "$1" != "-r" ]]; then
	echo -e; echo "Usage:"
	echo "$0 -i	- installs mark-installs"
	echo "$0 -u	- uninstalls mark-installs"
	echo "$0 -r	- reinstalls mark-installs"; echo -e
	exit 2
fi
if [[ "$1" = "-i" ]]; then
	if [[ -e /usr/local/bin/mark-installs ]]; then
		echo "mark-installs is already installed!"; echo -e
		exit 3
	else
		echo "Installing mark-installs"; echo -e
		gcc -o mark-installs mark-installs.c
		cp mark-installs /usr/local/bin/
		mkdir /home/PACKAGES/
		exit 0
	fi
else if [[ "$1" = "-u" ]]; then
	if [[ ! -e /usr/local/bin/mark-installs ]]; then
		echo "mark-installs is not installed yet!"; echo -e
		exit 3
	else
		echo "Uninstalling mark-installs"; echo -e
		rm /usr/local/bin/mark-installs
		exit 0
	fi
fi
if [[ "$1" = "-r" ]]; then
	if [[ ! -e /usr/local/bin/mark-installs ]]; then
		echo "mark-installs is not installed yet!"; echo -e
		exit 3
	else
		echo "Reinstalling mark-installs"; echo -e
		rm /usr/local/bin/mark-installs
		gcc -o mark-installs mark-installs.c
		cp mark-installs /usr/local/bin
		exit 0
	fi
fi
fi
exit 4
